# Generated by Django 5.0.7 on 2024-07-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=350, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('category', models.CharField(choices=[('AP', 'Appetizer'), ('MC', 'Main Course'), ('DS', 'Dessert'), ('BV', 'Beverage')], default='AP', max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Photo')),
            ],
        ),
    ]
