# Generated by Django 5.0.7 on 2024-07-21 14:59

from django.db import migrations

def create_products(apps):
    Product = apps.get_model('products', 'Product')
    
    products = [
        {'name': 'Spring Rolls', 'category': 'AP', 'price': 4.99, 'description': 'Crispy rolls filled with fresh vegetables and served with a tangy dipping sauce.', 'available': True},
        {'name': 'Caesar Salad', 'category': 'AP', 'price': 6.99, 'description': 'Classic Caesar salad with romaine lettuce, croutons, and Caesar dressing.', 'available': True},
        {'name': 'Beef Burger', 'category': 'MC', 'price': 10.99, 'description': 'Juicy beef patty with lettuce, tomato, and cheese on a toasted bun.', 'available': True},
        {'name': 'Grilled Chicken', 'category': 'MC', 'price': 12.99, 'description': 'Grilled chicken breast served with a side of steamed vegetables.', 'available': True},
        {'name': 'Chocolate Cake', 'category': 'DS', 'price': 5.99, 'description': 'Decadent chocolate cake with a rich and creamy chocolate frosting.', 'available': True},
        {'name': 'Ice Cream', 'category': 'DS', 'price': 3.99, 'description': 'Assorted flavors of creamy ice cream served in a bowl or cone.', 'available': True},
        {'name': 'Lemonade', 'category': 'BV', 'price': 2.99, 'description': 'Refreshing lemonade made with freshly squeezed lemons.', 'available': True},
        {'name': 'Coffee', 'category': 'BV', 'price': 1.99, 'description': 'Hot brewed coffee with the option of cream and sugar.', 'available': True},   
    ]
    for product_data in products:
        Product.objects.create(**product_data)
    
class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_products),
    ]
