# Generated by Django 5.0.7 on 2024-07-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_initial_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AP', 'Appetizer'), ('BV', 'Beverage'), ('DS', 'Dessert'), ('MC', 'Main Course')], default='AP', max_length=2, verbose_name='Category'),
        ),
    ]
